### PR TITLE
#11541. Streaming renegotiation

### PR DESCRIPTION
**Pull request by alber2510**
It's tested with webRTC commit: 9863f3d246e2da7a2e1f42bbc5757f6af5ec5682

This PR should be merged at the same time than:
- Android's PR: https://github.com/meganz/android2/pull/1048
- iOS PR: https://github.com/meganz/iOS_dev/pull/417
- SDK's PR: https://github.com/meganz/sdk/pull/1755

### CODE REVIEW

File: src/rtcModule/webrtcAdapter.h [hunk 1]
```diff
@@ -1,21 +1,23 @@
...
 #include "karereCommon.h" //only for std::string on android
 #include "base/promise.h"
 #include "webrtcAsyncWaiter.h"
 #include "rtcmPrivate.h"
+#include <rtc_base/ref_counter.h>
+
+#ifdef __OBJC__
+@class AVCaptureDevice;
+@class RTCCameraVideoCapturer;
+#else
```
[the remark this answers is not in the document]
Comment (javitrujillo) [reply src/rtcModule/webrtcAdapter.h]: I have just tested, it produces a compilation error:

```
/src/rtcModule/webrtcAdapter.h:404:5: Unknown type name 'AVCaptureDevice'
/src/rtcModule/webrtcAdapter.h:405:5: Unknown type name 'RTCCameraVideoCapturer'
```

File: src/rtcModule/webrtcAdapter.cpp [hunk 2]
```diff
@@ -51,7 +54,18 @@ bool init(void *appCtx)
     threadMgr->SetCurrentThread(thread);
 
     rtc::InitializeSSL();
-    gWebrtcContext = webrtc::CreatePeerConnectionFactory();
+    if (gWebrtcContext == nullptr)
+    {
+        gWebrtcContext = webrtc::CreatePeerConnectionFactory(
```
Comment (sergiohs84) [inline src/rtcModule/webrtcAdapter.cpp]: We should review the thread's management here, to ensure that it will not break the existing synchronization between MEGAchat's thread and WebRTC's thread/s.

File: src/rtcModule/webrtcAdapter.h [hunk 3]
```diff
@@ -250,190 +255,161 @@ class myPeerConnection: public
...
+    rtc::VideoBroadcaster mBroadcaster;
+    webrtc::MediaSourceInterface::SourceState mState;
+    bool mRemote;
+    rtc::scoped_refptr<webrtc::VideoCaptureModule> mCameraCapturer;
+    webrtc::VideoCaptureCapability mCapabilities;
+    mutable webrtc::webrtc_impl::RefCounter mRefCount{0};
 };
 
-class DeviceManager
+class CapturerTrackSource : public VideoManager
```
Comment (sergiohs84) [inline src/rtcModule/webrtcAdapter.h]: Probably this class can be removed in pro of a design where the `VideoManager` itself inherits from `VideoTrackSourceInterface`, which would result in a cleaner and simpler design.
Furthermore, it should help, as well, to avoid the issue with the destruction of the implementation of such interface, which is an object shared between Objective C and C++ / WebRTC.

File: src/rtcModule/webrtcAdapter.h [hunk 4]
```diff
@@ -250,190 +255,161 @@ class myPeerConnection: public
...
 {
 public:
-    struct InputDevices
-    {
-        DeviceList audio;
-        DeviceList video;
-    };
+    static CapturerTrackSource* Create(const webrtc::VideoCaptureCapability &capabilities, const std::string &deviceName);
+    ~CapturerTrackSource() override;
+    static std::set<std::pair<std::string, std::string>> getVideoDevices();
```
Comment (sergiohs84) [inline src/rtcModule/webrtcAdapter.h]: This method can also fit into the `VideoManager` as an static method.

File: src/rtcModule/OBJCCaptureModule.mm [hunk 5]
```diff
@@ -0,0 +1,157 @@
+
```
Comment (sergiohs84) [inline src/rtcModule/OBJCCaptureModule.mm]: We may want to add this file to the .pro, so it appears in the project inside QtCreator (despite it will not be compiled). It may help to browse the code and to read it, even when its compilation requires xCode

File: src/rtcModule/webrtcAdapter.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (alber2510) [reply src/rtcModule/webrtcAdapter.h]: Ok, we keep that lines

File: src/rtcModule/webrtcAdapter.cpp [hunk 6]
```diff
@@ -78,171 +88,382 @@ unsigned long generateId()
...
 
-    if (devices.size() == 0)
+    uint32_t numDevices = info->NumberOfDevices();
+    for (uint32_t i = 0; i < numDevices; i++)
     {
-        RTCM_LOG_WARNING("Not suitable input video devices were found. Default device added.");
-        devices.push_back(cricket::Device("default", "0"));
+        char deviceName[256];
+        char uniqueName[256];
+        std::unique_ptr<webrtc::VideoCaptureModule::DeviceInfo> deviceInfo(webrtc::VideoCaptureFactory::CreateDeviceInfo());
```
Comment (sergiohs84) [inline src/rtcModule/webrtcAdapter.cpp]: Cannot we use the `info` retrieved previously and simply iterate through the items and call `info->GetDeviceName()`??

File: src/rtcModule/webrtcAdapter.cpp [hunk 7]
```diff
@@ -78,171 +88,382 @@ unsigned long generateId()
...
-    MEGAjvm->AttachCurrentThread(&env, NULL);
-    rtc::Thread *currentThread = rtc::ThreadManager::Instance()->CurrentThread();
-    mSource = new rtc::RefCountedObject<webrtc::AndroidVideoTrackSource>(currentThread, env, surfaceTextureHelper, false);
-    rtc::scoped_refptr<webrtc::VideoTrackSourceProxy> proxySource = webrtc::VideoTrackSourceProxy::Create(currentThread, currentThread, mSource);
-    if (startVideoCaptureWithParametersMID)
+    mCameraCapturer->RegisterCaptureDataCallback(this);
+
+    std::unique_ptr<webrtc::VideoCaptureModule::DeviceInfo> deviceInfo(webrtc::VideoCaptureFactory::CreateDeviceInfo());
+    webrtc::VideoCaptureCapability capabilities;
+    deviceInfo->GetCapability(mCameraCapturer->CurrentDeviceName(), 0, capabilities);
```
Comment (sergiohs84) [inline src/rtcModule/webrtcAdapter.cpp]: Why don't we simply pass here `mCapabilities`?
```suggestion
    deviceInfo->GetCapability(mCameraCapturer->CurrentDeviceName(), 0, mCapabilities);
```
That way we only have to set the `videoType` and we would honor all the capabilities provided by `GetCapability()`, rather than request to `StartCapture()` with our hardcoded capabilities.

File: src/rtcModule/webrtcAdapter.cpp [hunk 8]
```diff
@@ -78,171 +88,382 @@ unsigned long generateId()
...
     {
-        std::string widthString;
-        mOptions->constraints.GetMandatory().FindFirst(webrtc::MediaConstraintsInterface::kMinWidth, &widthString);
-        int width = std::atoi(widthString.c_str());
-        std::string heightString;
-        mOptions->constraints.GetMandatory().FindFirst(webrtc::MediaConstraintsInterface::kMinHeight, &heightString);
-        int height = std::atoi(heightString.c_str());
-        int fps = 15;
-        env->CallStaticVoidMethod(applicationClass, startVideoCaptureWithParametersMID, (jint)width, (jint)height, (jint)fps, (jlong)proxySource.release(), surfaceTextureHelper);
+        return;
```
Comment (sergiohs84) [inline src/rtcModule/webrtcAdapter.cpp]: We should add an error message to the log here

File: src/rtcModule/webrtc.cpp [hunk 9]
```diff
@@ -2819,16 +2846,26 @@ void Session::veryfySdpOfferSendAnswer()
...
             return;
 
+        uint8_t opcode;
+        if (mState < kStateInProgress)
+        {
+            mTsSdpHandshakeCompleted = time(nullptr);
+            setState(kStateConnecting);
+            opcode = RTCMD_SDP_ANSWER;
+        }
+        else
```
Comment (sergiohs84) [inline src/rtcModule/webrtc.cpp]: Should we handle the `mState >= kStateTerminating` here?? Not sure if it's a valid state at this codepath.

File: src/rtcModule/webrtc.cpp [hunk 10]
```diff
@@ -2955,6 +2998,44 @@ void Session::onSignalingChange(webrtc::PeerConnectionInterface::SignalingState
...
+    }
+
+    if (mRenegotiationInProgress)
+    {
+        SUB_LOG_WARNING("Ignoring multiple calls of onRenegotiationNeeded");
+        return;
+    }
+
+    mRenegotiationInProgress = true;
+    setStreamRenegotiationTimeout();
```
Comment (sergiohs84) [inline src/rtcModule/webrtc.cpp]: I would move the `mRenegotiationInProgress = true;` into the method that actually sets the corresponding timer. I'll push a commit for that.

File: src/rtcModule/webrtc.cpp [hunk 11]
```diff
@@ -2975,13 +3056,21 @@ void Session::sendAv(AvFlags av)
...
     assert(mPeerAnonId);
     createRtcConn();
+    return sendOffer();
+}
+
+Promise<void> Session::sendOffer()
+{
     auto wptr = weakHandle();
-    return mRtcConn.createOffer(pcConstraints())
+    bool firstOffer = mState < kStateInProgress;
```
Comment (sergiohs84) [inline src/rtcModule/webrtc.cpp]: Suggestion: `bool isRenegotiation = mState == kStateInProgress;`
It seems more readable to me. I'll refactorize it.

File: src/rtcModule/webrtc.cpp [hunk 12]
```diff
@@ -2993,25 +3082,35 @@ Promise<void> Session::sendOffer()
...
 
-        SdpKey encKey;
-        mCall.mManager.crypto().encryptKeyTo(mPeer, mOwnHashKey, encKey);
         SdpKey hash;
         mCall.mManager.crypto().mac(mOwnSdpOffer, mPeerHashKey, hash);
 
-        // SDP_OFFER sid.8 anonId.8 encHashKey.32 fprHash.32 av.1 sdpLen.2 sdpOffer.sdpLen
-        cmd(RTCMD_SDP_OFFER,
+        SdpKey encKey;
+        uint8_t command = 0;
```
Comment (sergiohs84) [inline src/rtcModule/webrtc.cpp]: This is the `opcode`, not the command, indeed :P 
I'll refactorize it.

File: src/rtcModule/webrtcPrivate.h [hunk 13]
```diff
@@ -64,36 +98,45 @@ class Session: public ISession
     unsigned int mPreviousStatsSize = 0;
     std::unique_ptr<AudioLevelMonitor> mAudioLevelMonitor;
     TermCode mTermCode = TermCode::kInvalid;
+    bool mPeerSupportRenegotiation = false;
+    bool mRenegotiationInProgress = false;
```
Comment (sergiohs84) [inline src/rtcModule/webrtcPrivate.h]: I wonder if this flag should be a new state of the session/call, rather than a state's flag. Let's discuss about it.

File: webrtc-build/CMakeLists.txt [hunk 14]
```diff
@@ -51,7 +51,7 @@ set(WEBRTC_DEFS_LINUX
     -DLINUX -DWEBRTC_POSIX=1 -DHASH_NAMESPACE=__gnu_cxx -DPOSIX -DDISABLE_DYNAMIC_CAST
     -DSSL_USE_NSS -DHAVE_NSS_SSL_H -DSSL_USE_NSS_RNG -DUSE_NSS=1
     -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1
-    -DBLINK_SCALE_FILTERS_AT_RECORD_TIME -D_FILE_OFFSET_BITS=64 -DTOOLKIT_VIEWS=1
+    -DBLINK_SCALE_FILTERS_AT_RECORD_TIME -DUNVALID_FILE_OFFSET_BITS=64 -DTOOLKIT_VIEWS=1
```
[the remark this answers is not in the document]
Comment (alber2510) [reply webrtc-build/CMakeLists.txt]: I'll remove and check compilation in all platforms

File: src/rtcModule/webrtc.cpp [hunk 15]
```diff
@@ -2955,6 +2998,49 @@ void Session::onSignalingChange(webrtc::PeerConnectionInterface::SignalingState
...
+    }
+}
+
+void Session::onRenegotiationNeeded()
+{
+    if (mState != kStateInProgress)
+    {
+        if (mState < kStateInProgress)
+        {
+            mRenegotiationAfterInitialConnect = true;
```
[the remark this answers is not in the document]
Comment (alber2510) [reply src/rtcModule/webrtc.cpp]: It's ok

File: src/rtcModule/webrtcAdapter.cpp (hunk 7 above)
Comment (sergiohs84) [reply src/rtcModule/webrtcAdapter.cpp]: The `mCapabilities` is already fixed to the wanted video resolution and fps. Only the `interlaced` capability needs to be the same than the supported by the device. The video format is preset to `I420` because that's the output video format, so we can avoid the conversion of frames from another format.

File: src/rtcModule/webrtcAdapter.cpp (hunk 8 above)
Comment (alber2510) [reply src/rtcModule/webrtcAdapter.cpp]: Fixed

File: src/rtcModule/webrtc.cpp [hunk 16]
```diff
@@ -221,16 +146,49 @@ void RtcModule::removeCallRetry(karere::Id chatid)
...
+    std::set<std::pair<std::string, std::string>> videoDevices = loadDeviceList();
+    for (const std::pair<std::string, std::string> &device : videoDevices)
+    {
+        if (mVideoDeviceSelected == device.second)
+        {
+            return device.first;
+        }
+    }
+
+    return std::string();
```
[the remark this answers is not in the document]
Comment (alber2510) [reply src/rtcModule/webrtc.cpp]: Fixed, by protecting _openDevice_

File: src/rtcModule/webrtc.cpp [hunk 17]
```diff
@@ -2223,6 +2100,105 @@ void Call::monitorCallSetupTimeout()
...
+
+void Call::enableVideo(bool enable)
+{
+    if (mState >= Call::kStateTerminating)
+    {
+        return;
+    }
+
+    if (enable)
+    {
```
[the remark this answers is not in the document]
Comment (alber2510) [reply src/rtcModule/webrtc.cpp]: It's created at beginning of the call

File: src/rtcModule/webrtc.cpp (hunk 9 above)
Comment (alber2510) [reply src/rtcModule/webrtc.cpp]: It's checked few lines above

File: src/rtcModule/webrtcPrivate.h (hunk 13 above)
Comment (alber2510) [reply src/rtcModule/webrtcPrivate.h]: It's not really necessary, session is terminating when the flag is set

File: webrtc-build/CMakeLists.txt (hunk 14 above)
[the remark this answers is not in the document]
Comment (alber2510) [reply webrtc-build/CMakeLists.txt]: The flags are not necessary
